spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/bootcamp
    username: postgres
    password: admin
  jpa:
    hibernate:
      ddl-auto: update
security:
  oauth2:
    resource:
      filter-order: 3
---
#spring:
#  profiles: production
#  datasource:
#    driver-class-name: org.postgresql.Driver
#    url: jdbc:postgresql://localhost:5432/training
#    username: lukaszandrzejewski
#  jpa:
#    hibernate:
#      ddl-auto: update